/**
 * @hvl/vite - Route scanner
 * Scans the routes directory and generates a route map.
 * Produces the virtual:routes module.
 */

import type { RouteEntry } from './types.js'
import { readdir, stat } from 'node:fs/promises'
import { join, sep, posix } from 'node:path'

/**
 * Convert a file path to a URL path pattern.
 * e.g., 'index.ts' → '/', 'about.ts' → '/about', 'posts/[id].ts' → '/posts/:id'
 */
function filePathToRoutePath(filePath: string): string {
  // Normalize separators
  let p = filePath.split(sep).join(posix.sep)

  // Remove extension
  p = p.replace(/\.[^.]+$/, '')

  // Convert [param] to :param
  p = p.replace(/\[([^\]]+)\]/g, ':$1')

  // Handle index
  if (p === 'index') return '/'
  if (p.endsWith('/index')) p = p.slice(0, -6) // Remove trailing /index

  // Ensure leading slash
  if (!p.startsWith('/')) p = '/' + p

  return p
}

/**
 * Determine route type from file path.
 * Files under 'api/' subdirectory are API routes.
 */
function getRouteType(filePath: string): 'page' | 'api' {
  const normalized = filePath.split(sep).join(posix.sep)
  return normalized.startsWith('api/') || normalized.includes('/api/') ? 'api' : 'page'
}

/**
 * Generate a valid JS variable name from a route path.
 * e.g., '/' → 'RouteIndex', '/about' → 'RouteAbout', '/posts/:id' → 'RoutePostsId'
 */
function pathToVarName(path: string): string {
  let name = path
    .replace(/^\//, '')
    .replace(/\/$/, '')
    .replace(/:([^/]+)/g, '$1')
    .replace(/[^a-zA-Z0-9]/g, '_')
  if (!name || name === '_') name = 'Index'
  return 'Route_' + name.charAt(0).toUpperCase() + name.slice(1)
}

/**
 * Check if a file should be ignored for routing.
 * Files starting with _ are special (layout, middleware, etc.)
 */
function isSpecialFile(fileName: string): boolean {
  return fileName.startsWith('_') || fileName.startsWith('.')
}

/**
 * Recursively scan a directory for route files.
 */
export async function scanRoutes(
  routesDir: string,
  baseDir: string = ''
): Promise<RouteEntry[]> {
  const entries: RouteEntry[] = []
  let files: string[]

  try {
    files = await readdir(routesDir)
  } catch {
    // Directory doesn't exist yet — return empty
    return entries
  }

  for (const file of files) {
    if (file.startsWith('.')) continue

    const fullPath = join(routesDir, file)
    const relativePath = baseDir ? join(baseDir, file) : file
    const fileStat = await stat(fullPath)

    if (fileStat.isDirectory()) {
      // Recurse into subdirectories
      const subEntries = await scanRoutes(fullPath, relativePath)
      entries.push(...subEntries)
    } else if (isSpecialFile(file)) {
      // Skip _renderer.ts, _middleware.ts, etc.
      continue
    } else if (/\.(ts|tsx|js|jsx)$/.test(file)) {
      // It's a route file
      const routePath = filePathToRoutePath(relativePath)
      entries.push({
        path: routePath,
        filePath: relativePath.split(sep).join(posix.sep),
        type: getRouteType(relativePath),
        varName: pathToVarName(routePath),
      })
    }
  }

  // Sort routes: static paths first, then dynamic
  entries.sort((a, b) => {
    const aDynamic = a.path.includes(':')
    const bDynamic = b.path.includes(':')
    if (aDynamic !== bDynamic) return aDynamic ? 1 : -1
    return a.path.localeCompare(b.path)
  })

  return entries
}

/**
 * Generate the virtual:routes module code.
 */
export function generateRoutesModule(routes: RouteEntry[], routesDir: string): string {
  const imports = routes
    .map(r => `import * as ${r.varName} from '/${routesDir}/${r.filePath}';`)
    .join('\n')

  const routeDefs = routes
    .map(
      r =>
        `  { path: '${r.path}', filePath: '${r.filePath}', type: '${r.type}', module: ${r.varName} },`
    )
    .join('\n')

  return `// Auto-generated by @hvl/vite route-scanner
// DO NOT EDIT — changes will be overwritten

${imports}

export const routes = [
${routeDefs}
];

export const pageRoutes = routes.filter(r => r.type === 'page');
export const apiRoutes = routes.filter(r => r.type === 'api');
`
}

/**
 * Generate the virtual:islands module code.
 */
export function generateIslandsModule(
  islandsDir: string,
  islandFiles: string[]
): string {
  const imports = islandFiles
    .map((f, i) => {
      const tagName = fileToTagName(f)
      return `import * as Island_${i} from '/${islandsDir}/${f}';`
    })
    .join('\n')

  const islandDefs = islandFiles
    .map((f, i) => {
      const tagName = fileToTagName(f)
      return `  { tagName: '${tagName}', modulePath: '/${islandsDir}/${f}', module: Island_${i} },`
    })
    .join('\n')

  return `// Auto-generated by @hvl/vite island-scanner
// DO NOT EDIT — changes will be overwritten

${imports}

export const islands = [
${islandDefs}
];

export const islandTagNames = islands.map(i => i.tagName);
`
}

/**
 * Convert a file name to a Custom Element tag name.
 * e.g., 'my-counter.ts' → 'my-counter', 'theme-toggle.ts' → 'theme-toggle'
 */
export function fileToTagName(fileName: string): string {
  return fileName.replace(/\.[^.]+$/, '')
}

/**
 * Scan islands directory for island files.
 */
export async function scanIslands(islandsDir: string): Promise<string[]> {
  const files: string[] = []
  let entries: string[]

  try {
    entries = await readdir(islandsDir)
  } catch {
    return files
  }

  for (const entry of entries) {
    if (entry.startsWith('.')) continue
    if (/\.(ts|tsx|js|jsx)$/.test(entry)) {
      files.push(entry)
    }
  }

  return files.sort()
}
